### ISSUE TITLE
gsl_stats_correlation

### ISSUE THREAD

**Issue by poflawless** [smithlabcode/radmeth#3]
when I try to make radmeth, it encountered the following issues, while I have no idea to do.
$ make
make -C src/adjust/
make[1]: ino the directory “/home/experiment/tools/radmeth-master/src/adjust”
/usr/bin/g++ -g -Wall -Wextra -pthread -c -o distance_correlation.o distance_correlation.cpp -I../../smithlab_cpp/
distance_correlation.cpp: function‘double DistanceCorrelation::correlation(const std::vector<double>&, const std::vector<double>&)’中:
distance_correlation.cpp:86:17: error：‘gsl_stats_correlation’has not been declared
   double corr = gsl_stats_correlation( gsl_x.vector.data, stride,
                 ^~~~~~~~~~~~~~~~~~~~~
distance_correlation.cpp:86:17: annotate：suggested alternative: ‘gsl_stats_char_min’
   double corr = gsl_stats_correlation( gsl_x.vector.data, stride,
                 ^~~~~~~~~~~~~~~~~~~~~
                 gsl_stats_char_min
make[1]: *** [distance_correlation.o] error 1
make[1]: leave out “/home/experiment/tools/radmeth-master/src/adjust”
make: *** [all] error 2

**Comment by andrewdavidsmith** [comment]
Thanks @poflawless Which way did you install GSL? Or did you check that it was already available on your system?

**Comment by poflawless** [comment]
I download the gsl from this link ftp://ftp.gnu.org/gnu/gsl/gsl-1.0.tar.gz
 and  sudo ./configure
sudo make
sudo make install and make test and tests were passed

**Comment by andrewdavidsmith** [comment]
Ok. Thanks. Just as another check, can you try running `gsl-randist` at the command line -- no arguments, just to check that it's in your path somewhere? Also, if you could try to download the methpipe software that would help. I think we have moved all updates to radmeth into the methpipe repo. It will be easier for me to help you from there. Also, if you could post the result of `uname -a` that would help, and depending on your system, the result of `whereis gsl` might help. I can try on some of my other systems to see if I can reproduce the problem.

**Comment by poflawless** [comment]
when I run gsl-randist 
1 gsl-randist 
Usage: gsl-randist seed n DIST param1 param2 ...
Generates n samples from the distribution DIST with parameters param1,
param2, etc. Valid distributions are,

  beta
  binomial
  bivariate-gaussian
  cauchy
  chisq
  dir-2d
  dir-3d
  dir-nd
  erlang
  exponential
  exppow
  fdist
  flat
  gamma
  gaussian-tail
  gaussian
  geometric
  gumbel1
  gumbel2
  hypergeometric
  laplace
  landau
  levy
  levy-skew
2 [experiment@lin radmeth-master]$ uname -a
Linux lin 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
3 [experiment@lin radmeth-master]$ whereis gsl
gsl: /usr/include/gsl /usr/share/man/man3/gsl.3.gz
4  I have tried the methpipe whereas the the same error info occurred
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/analysis”
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/utils”
make[2]: “all”nothing to do。
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/utils”
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/amrfinder”
make[2]: “all”nothing to do。
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/amrfinder”
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/mlml”
make[2]: “all” nothing to do。
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/mlml”
make[2]: “/home/experiment/tools/methpipe-3.4.3/src/radmeth”
g++ -Wall -fmessage-length=50 -std=c++11 -O2 -c -o combine_pvals.o combine_pvals.cpp -I/home/experiment/tools/methpipe-3.4.3/src/smithlab_cpp -I../common
combine_pvals.cpp: function
   ‘double 
   DistanceCorrelation::correlation(const 
   std::vector<double>&, const 
   std::vector<double>&)’中:
combine_pvals.cpp:225:17: error：‘gsl_stats_correlation’
  has not been declared
   double corr = gsl_stats_correlation
( gsl_x.vector.data, stride,
                 ^~~~~~~~~~~~~~~~~~~~~

combine_pvals.cpp:225:17: annotate：suggested
   alternative: 
   ‘gsl_stats_char_min’
   double corr = gsl_stats_correlation
( gsl_x.vector.data, stride,
                 ^~~~~~~~~~~~~~~~~~~~~

                 gsl_stats_char_min
make[2]: *** [combine_pvals.o] error 1
make[2]: leave“/home/experiment/to

**Comment by poflawless** [comment]
Dear Andrew Smith,

 

   Thank you for your help. I have tried several methods to solve this issue, while the problem was still there. Could you please transfer pre-compiled banaries radmeth files to me ? Thank you again for your help.




Best Wishes,




poflawless












-----原始邮件-----
发件人:"Andrew Smith" <notifications@github.com>
发送时间:2019-04-23 22:57:14 (星期二)
收件人: smithlabcode/radmeth <radmeth@noreply.github.com>
抄送: poflawless <poflawless@cau.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [smithlabcode/radmeth] gsl_stats_correlation (#3)



Ok. Thanks. Just as another check, can you try running gsl-randist at the command line -- no arguments, just to check that it's in your path somewhere? Also, if you could try to download the methpipe software that would help. I think we have moved all updates to radmeth into the methpipe repo. It will be easier for me to help you from there. Also, if you could post the result of uname -a that would help, and depending on your system, the result of whereis gsl might help. I can try on some of my other systems to see if I can reproduce the problem.

**Comment by andrewdavidsmith** [comment]
@poflawless Please send me a direct email for such a request.
