### ISSUE TITLE
How to do paired DM analysis?

### ISSUE THREAD

**Issue by bishwaG** [smithlabcode/radmeth#4]
Hi,
I have matched pair experimental design. I would like to compare treatment groups. How can i perform paired differential mehtylation analysis using radmeth?

```
sample	treatment	donor
s1	ctl	A
s2	t1	A
s3	t2	A
s4	ctl	B
s5	t1	B
s6	t2	B
s7	ctl	C
s8	t1	C
s9	t2	C
```

Best,
BishwaG

**Comment by andrewdavidsmith** [comment]
@bishwaG If this is a question about usage, rather than about the source code, can you please submit it to the MethPipe Google group? I'll try to answer asap. Thanks.
